//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SellPointEntities : DbContext
    {
        public SellPointEntities()
            : base("name=SellPointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entidades> Entidades { get; set; }
        public virtual DbSet<GruposEntidades> GruposEntidades { get; set; }
        public virtual DbSet<tblRolUserEntidad> tblRolUserEntidades { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
        public virtual DbSet<tblTipoDocumento> tblTipoDocumento { get; set; }
        public virtual DbSet<tblTipoEntidad> tblTipoEntidad { get; set; }
        public virtual DbSet<TiposEntidades> TiposEntidades { get; set; }
    }
}
