//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidades
    {
        public int IdEntidad { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public int TipoEntidad { get; set; }
        public int TipoDocumento { get; set; }
        public decimal NumeroDocumento { get; set; }
        public string Telefonos { get; set; }
        public string URLPaginaWeb { get; set; }
        public string URLFacebook { get; set; }
        public string URLInstagram { get; set; }
        public string URLTwitter { get; set; }
        public string URLTikTok { get; set; }
        public Nullable<decimal> IdGrupoEntidad { get; set; }
        public Nullable<decimal> IdTipoEntidad { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public string UserNameEntidad { get; set; }
        public string PasswordEntidad { get; set; }
        public Nullable<int> RolUserEntidad { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> NoEliminable { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual GruposEntidades GruposEntidades { get; set; }
        public virtual TiposEntidades TiposEntidades { get; set; }
        public virtual tblRolUserEntidad tblRolUserEntidad { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual tblTipoDocumento tblTipoDocumento { get; set; }
        public virtual tblTipoEntidad tblTipoEntidad { get; set; }

        public string statement { get; set; }
    }
}
