//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposEntidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposEntidades()
        {
            this.Entidades = new HashSet<Entidades>();
        }
    
        public decimal IdTipoEntidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> IdGrupoEntidad { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> NoEliminable { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidades> Entidades { get; set; }
        public virtual GruposEntidades GruposEntidades { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
